export const DISHES_LOADING = 'DISHES_LOADING';
export const LOAD_DISHES = 'LOAD_DISHES';
export const DISHES_FAILED = 'DISHES_FAILED';

export const PROMOS_LOADING = 'PROMOS_LOADING';
export const LOAD_PROMOS = 'LOAD_PROMOS';
export const PROMOS_FAILED = 'PROMOS_FAILED';

export const LEADERS_LOADING = 'LEADERS_LOADING';
export const LOAD_LEADERS = 'LOAD_LEADERS';
export const LEADERS_FAILED = 'LEADERS_FAILED';

export const ADD_USER ="ADD_USER";
export const REGISTER_FAILED ="REGISTER_FAILED";

export const LOGIN_FAILED ="LOGIN_FAILED";
export const LOGOUT_USER ="LOGOUT_USER";
export const REDIRECT_USER ="REDIRECT_USER";

export const POST_FAVORITE = 'POST_FAVORITE';
export const ADD_FAVORITE = 'ADD_FAVORITE';

export const ADD_COMMENT = 'ADD_COMMENT';
export const UPDATE_DISHES = 'UPDATE_DISHES';

